### PR TITLE
Updated php and extensions to php7.2 from php7.0

### PR DESCRIPTION
**Pull request by topherbuckley**
This is in line with the version quoted from the [requirements page](https://docs.kanboard.org/en/latest/admin_guide/requirements.html)

### CODE REVIEW

**Comment by fguillot** [comment]
This is the installation instructions for Ubuntu 16.04. Does this version offers PHP 7.2?

**Comment by topherbuckley** [comment]
Good catch! Sorry, yes I'm on 18.04. Didn't pay attention to the subheader in the docs (Main header just says "Installation on Ubuntu". 

Apparently 16.04 defaults to php7.0, but it can be upgraded to 7.2 via [these instructions](https://www.liquidweb.com/kb/install-php-7-2-ubuntu-16-04/)

Would you like me to add a second subsection to include 18.04 and leave 16.04 as is and/or update 16.04 to include instructions for updating to php7.2 to match the [requirements](https://docs.kanboard.org/en/latest/admin_guide/requirements.html#php-versions)? It seems a bit confusing to state Kanboard only works with php7.2+ but then provide instructions to install php7.0 elsewhere. Thoughts?

**Comment by fguillot** [comment]
It would be better to update the installation instructions for latest Ubuntu LTS. This page hasn't been updated for a while.

If the rest of the page still accurate then you just need to change the subtitle to Ubuntu 18.04.

**Comment by topherbuckley** [comment]
Alright. Changed the subtitle. The rest of the instructions look similar to how I installed, i.e. nothing obvious looks out of date to me.

**Pull request merged**
